"""criar tabela documents

Revision ID: 0652a0711e3e
Revises: 0bc0e7c3f392
Create Date: 2026-02-03 20:52:21.151467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0652a0711e3e'
down_revision: Union[str, Sequence[str], None] = '0bc0e7c3f392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
